baseURL = "https://the-zen-of-prometheus.netlify.app/"
languageCode = "en"
DefaultContentLanguage = "en"
title = "The Zen of Prometheus"
theme = "anatole"
summarylength = 10
enableEmoji = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

[params]
title = "The Zen of Prometheus"
author = "The Zen of Prometheus"
description = "Simple, Poetic, Illuminating."
profilePicture = "images/prometheus.svg"
keywords = ""
favicon = "favicons/"
customCss = []
mainSections = ["home"]

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
[[params.socialIcons]]
icon = "fa-github"
title = "GitHub"
url = "https://github.com/kakkoyun/the-zen-of-prometheus"

## Menu items

[menu]
  [[menu.main]]
  name = ""
  identifier = "home"
  weight = 100
  url = "/"

